services:
  - type: web
    name: ekalipi-tts
    env: python
    buildCommand: |
      git lfs pull
      pip install --upgrade pip
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt')"
      mkdir -p static/audio tmp
    startCommand: gunicorn app:app --config gunicorn_config.py --timeout 120 --workers 1 --threads 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 4005
      - key: GUNICORN_TIMEOUT
        value: 120
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: MALLOC_TRIM_THRESHOLD_
        value: 0  # Help manage memory usage
      - key: FLASK_ENV
        value: production
    plan: free
    healthCheckPath: /
    healthCheckTimeout: 100