name: ekalipi-tts
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
    build_command: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt')"
      mkdir -p static/audio tmp
    run_command: python app.py
    instance_size_slug: basic-xxs
    instance_count: 1
    env:
      - key: PORT
        value: "8080"
      - key: FLASK_APP
        value: "app.py"
      - key: FLASK_ENV
        value: "production"
    health_check:
      http_path: /
      initial_delay_seconds: 20
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3